 export const LOGIN_ROUTE = '/login'
 export const MAIN_ROUTE = '/'
 export const SIGNL_ROUTE = '/signl'
 export const ADDL_ROUTE = '/addl'
 export const PROF_ROUTE = '/profile'
 export const REG_ROUTE = '/registration'
